apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: link-shortener
  template:
    metadata:
      labels:
        app: link-shortener
    spec:
      containers:
        - name: link-shortener
          image: umtcn/link-shortener:latest
          ports:
            - containerPort: 8080